### ISSUE TITLE
Add wind vector and day-night cycle.

### ISSUE THREAD

**Issue by Lexpartizan** [danilw/godot-utils-and-other#1]
I've taken out the wind direction vector in uniform and added a day and night cycle if you're interested. Thanks for your code. 
You can download my project for godot with this additions here.
https://yadi.sk/d/r-GuhpJQkr3TfQ

**Comment by danilw** [comment]
nice!
Tip: host it on github your code by you self, so other people can find it and use

I keep this shader as it is

**Comment by Lexpartizan** [comment]
Thank you, I took Your advice. And thank you for Your wonderful shader. 

Another thing. Is it possible to make so that with an increase in THICKNESS, the upper layers of the clouds are drawn first, and then the lower ones, and not vice versa, as now? Because the clouds are hanging too low, it seems that you touch their your head.

**Comment by danilw** [comment]
its not "my shader"(link to original shadertoy shade linked in shader code)

my is only adaptation to Godot and my "reflection logic"...thanks anyway xD

>Another thing.

check shadertoy website, there many "cloud shaders" you can learn then

also I have other "full dynamic day/night cycle" shader that almost loop-less(performance 10x faster then this one)
you can check how it look like on https://youtu.be/jTmppCifnYE
source in this project *godot-utils-and-other/a_rel_bw_game*

**Comment by Lexpartizan** [comment]
Big Thanks for your adaptation, anyway. Without your code I would be forced to use a simple texture. Without a cycle of day and night, etc., etc. And now I have the sky, as in Morrowind, thanks to you))

Other shader looks much worse, but it can be used for cell phones. I trying them. Thanks.
And thanks for your article on Habr)) Happy New Year!

**Comment by danilw** [comment]
thank 
nice to know that it useful for you :)
