### ISSUE TITLE
crash with particle collision 2d demo

### ISSUE THREAD

**Issue by zhaishengfu** [danilw/godot-utils-and-other#2]
hello, i rebuild the godot and run your demo, it is normal . but when i click spawn 1 or spawn rnd, the program will crash with only information that says:
![image](https://user-images.githubusercontent.com/7630101/84372685-12041b00-ac0e-11ea-89a4-5517f6bba250.png)

I used 3.2 stable version.

**Comment by zhaishengfu** [comment]
And can you give me some information about the principle of your methods? I see the shadertoy but not find any principle. I only know each particle has unique index...

**Comment by danilw** [comment]
Hello.

You talk about **particle_self_collision** from this repository?

>when i click spawn 1 or spawn rnd, the program will crash with only information that says:

What GPU you use?
I have no problem launching it, does **[linked web-demo](https://danilw.github.io/godot-utils-and-other/particle_self_collision/minimal_example/web_demo/mini_example.html)** work for you?

I did not check it in Godot 3.2, I do not think there should be any problem, can you try prebuild Web or .exe version?

>And can you give me some information about the principle of your methods? I see the shadertoy but not find any principle. I only know each particle has unique index...

Source code is very simple, I will not teach you "how shaders work", I think information on its shadertoy shader enough for understand it.

To more information you can check my post in Russian language about this code https://habr.com/ru/post/474676/
Proper educational resource about this method is this link on [Research Article](https://cyberleninka.ru/article/n/algoritmy-obnaruzheniya-stolknoveniy) also in Russian. I do not have english resource for this, google yourself.

**Comment by zhaishengfu** [comment]
thanks for your reply. the web demo is ok for me , and my gpu is nvidia 1050, i think it is not the problem of GPU.
yes, i only want to know the principle . I know clearly how shader works. https://habr.com/ru/post/474676/
this link is perfect for me . thank you very much .
for the crash problem, I will look carefully in to the code and if i have progress, i will tell you

**Comment by danilw** [comment]
Okay I check latter today this project in Godot 3.2, to see if my code has any problem on Godot side.

Will reply latter

**Comment by danilw** [comment]
Yes, it was a bug, thanks. Fixed now.
