### ISSUE TITLE
Clean up readme

### ISSUE THREAD

**Issue by AngelOnFira** [danilw/godot-utils-and-other#3]
Hi :wave: 

This is a really great repo for seeing a demo of some Godot stuff. The readme is a bit difficult to navigate though. I was wondering if I cleaned it up and made a PR if it would be considered to be accepted? Just wondering if you'd allow external contributors :smiley:

**Comment by danilw** [comment]
well if you want to invest your time into it, then I will accept it

or you can make your own repository base on my, with adding your code and fix my bad code, if you want to make "better for learning" examples, this option better for you. (and publish it by your self ofc, I do not care how this code used, feel free to copy it)

this repo exists only for my self, this is not learning stuff, if you or someone else found it useful - good for you

**Comment by AngelOnFira** [comment]
I understand. I see that there are 120 stars on this project, so I think quite a few people have seen it as a reference. If you prefer to keep it just as your own code repo, I'll find an alternative instead :smiley:
