### ISSUE TITLE
Dynamic Sky emit green color

### ISSUE THREAD

**Issue by fabriceci** [danilw/godot-utils-and-other#4]
I use the latest Godot version on mac (Catalina), if I run the dynamic sky demo, the sky emits a green light.

This behaviour only happens on Mac. I tested on two different mac (I don't have the issue if I run on windows)

Video: https://streamable.com/w3v6vs

Is-it shadder problem or a Godot one?
Is-there a way to force a default light color?

**Comment by danilw** [comment]
Hello
can you test this project on your Mac
[try in webbrowser on Mac](https://danilw.github.io/godot-utils-and-other/dyn_sky_refl/web_sky_ref_gles2/dsr.html)

**download** [source code zip](https://danilw.github.io/godot-utils-and-other/dyn_sky_refl/Dyn_Sky_only_GLES2.zip)

this is GLES2 version without reflections

**Comment by fabriceci** [comment]
Thanks for your answer.

I opened an issue here [https://github.com/godotengine/godot/issues/39952](https://github.com/godotengine/godot/issues/39952). I found that just with a texture (no shader) as viewport panorama, the bug appears.

**Comment by danilw** [comment]
thanks, so it fixed then :)
