### ISSUE TITLE
Sky rendering issues on mobile

### ISSUE THREAD

**Issue by slasktotten** [danilw/godot-utils-and-other#5]
Hi!

Not sure if it mobile is meant to be supported but we haven't been able to make the sky shader play nicely on either Android or iOS.
On android we get the blue gradient and on ios it goes completely black.

**Comment by danilw** [comment]
Hello, have you tried GLES2 version of sky shader?
https://danilw.github.io/godot-utils-and-other/dyn_sky_refl/web_sky_ref_gles2/dsr.html

its source https://danilw.github.io/godot-utils-and-other/dyn_sky_refl/Dyn_Sky_only_GLES2.zip

my original project made only for PC and to have real time reflection, this why Sky render in its own viewport
if you need Only SKY then use GLES2 version, there only shader that should work everywhere.

**Comment by danilw** [comment]
il close this if @slasktotten does not answer in one week

**Comment by danilw** [comment]
closed, as I say GLES2 version should fix it @slasktotten
