### ISSUE TITLE
 Link missing

### ISSUE THREAD

**Issue by RicoCruzSuave** [danilw/godot-utils-and-other#7]
https://github.com/danilw/godot-utils-and-other/blob/84364b0544af7480364250505387066bab0d02fd/particle_self_collision/mini_example/scripts/scene.gd#L33

**Comment by danilw** [comment]
thanks, but I dont remember why I have this comment there
it was 2+ year ago... (I had blog post in russian language about this demo, it was deleted, maybe I wanted to put it there... )

If you look for "information" about this:

1. Check this shader it should explain everything https://www.shadertoy.com/view/tstSz7
2. Building process for Godot engine modification (32 bit fbo) explained on this link https://github.com/danilw/flat-maze
3. Il make some blog post with explaining this my demos, and update some bad momments... but latter... (few weeks latter)

**If you still need some information/have questions - better just ask me in discord** (link to join to discord in comments on this repo page)

**il not close this Issue, this is TODO to make blogpost...**

**Comment by danilw** [comment]
Fixed by https://github.com/danilw/godot-utils-and-other/commit/80bb2da13861eb6d14dcff9eceae31d18d505279
